export const FALLBACK_MEDICINES = [
  {
    id: 'fallback-tablet-paracetamol-acetaminophen-500mg',
    name: 'Paracetamol / Acetaminophen 500mg',
    price: 25,
    description: 'Commonly used for acetaminophen care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=800&auto=format&fit=crop',
    dosage: '500 mg',
    packQuantity: 10,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 100,
  },
  {
    id: 'fallback-tablet-ibuprofen-400mg',
    name: 'Ibuprofen 400mg',
    price: 32,
    description: 'Commonly used for ibuprofen care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1576073719710-0a1b51853db5?q=80&w=800&auto=format&fit=crop',
    dosage: '400 mg',
    packQuantity: 10,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 75,
  },
  {
    id: 'fallback-tablet-cetirizine-10mg',
    name: 'Cetirizine 10mg',
    price: 22,
    description: 'Commonly used for cetirizine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-ad5f9fb072b2?q=80&w=800&auto=format&fit=crop',
    dosage: '10 mg',
    packQuantity: 10,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 120,
  },
  {
    id: 'fallback-tablet-metformin-500mg',
    name: 'Metformin 500mg',
    price: 30,
    description: 'Commonly used for metformin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1584017947474-1770d38f0e5e?q=80&w=800&auto=format&fit=crop',
    dosage: '500 mg',
    packQuantity: 15,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 90,
  },
  {
    id: 'fallback-tablet-amlodipine-5mg',
    name: 'Amlodipine 5mg',
    price: 40,
    description: 'Commonly used for amlodipine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1606206591513-bc15147963f5?q=80&w=800&auto=format&fit=crop',
    dosage: '5 mg',
    packQuantity: 10,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 90,
  },
  {
    id: 'fallback-tablet-lisinopril-10mg',
    name: 'Lisinopril 10mg',
    price: 45,
    description: 'Commonly used for lisinopril care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1607619113174-a29c314d1135?q=80&w=800&auto=format&fit=crop',
    dosage: '10 mg',
    packQuantity: 28,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 80,
  },
  {
    id: 'fallback-tablet-atorvastatin-20mg',
    name: 'Atorvastatin 20mg',
    price: 55,
    description: 'Commonly used for atorvastatin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1626082854244-031c172ac7d6?q=80&w=800&auto=format&fit=crop',
    dosage: '20 mg',
    packQuantity: 30,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 65,
  },
  {
    id: 'fallback-tablet-levothyroxine-100mcg',
    name: 'Levothyroxine 100mcg',
    price: 38,
    description: 'Commonly used for levothyroxine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?q=80&w=800&auto=format&fit=crop',
    dosage: '100 mcg',
    packQuantity: 30,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 110,
  },
  {
    id: 'fallback-tablet-losartan-50mg',
    name: 'Losartan 50mg',
    price: 42,
    description: 'Commonly used for losartan care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1624727828489-a1e03b79bba8?q=80&w=800&auto=format&fit=crop',
    dosage: '50 mg',
    packQuantity: 30,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 70,
  },
  {
    id: 'fallback-tablet-albuterol-tablet-4mg',
    name: 'Albuterol Tablet 4mg',
    price: 28,
    description: 'Commonly used for albuterol care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?q=80&w=800&auto=format&fit=crop',
    dosage: '4 mg',
    packQuantity: 10,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 50,
  },
  {
    id: 'fallback-tablet-prednisone-5mg',
    name: 'Prednisone 5mg',
    price: 15,
    description: 'Commonly used for prednisone care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=800&auto=format&fit=crop',
    dosage: '5 mg',
    packQuantity: 10,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 150,
  },
  {
    id: 'fallback-tablet-gabapentin-300mg',
    name: 'Gabapentin 300mg',
    price: 60,
    description: 'Commonly used for gabapentin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1618961734760-466979cb35b0?q=80&w=800&auto=format&fit=crop',
    dosage: '300 mg',
    packQuantity: 30,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 40,
  },
  {
    id: 'fallback-tablet-amoxicillin-tablet-500mg',
    name: 'Amoxicillin Tablet 500mg',
    price: 35,
    description: 'Commonly used for amoxicillin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1550572017-0bed8c807fb5?q=80&w=800&auto=format&fit=crop',
    dosage: '500 mg',
    packQuantity: 20,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 100,
  },
  {
    id: 'fallback-tablet-sertraline-50mg',
    name: 'Sertraline 50mg',
    price: 50,
    description: 'Commonly used for sertraline care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbbb88?q=80&w=800&auto=format&fit=crop',
    dosage: '50 mg',
    packQuantity: 30,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 55,
  },
  {
    id: 'fallback-tablet-montelukast-10mg',
    name: 'Montelukast 10mg',
    price: 33,
    description: 'Commonly used for montelukast care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1628243344933-2882a7f5aeb4?q=80&w=800&auto=format&fit=crop',
    dosage: '10 mg',
    packQuantity: 30,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 85,
  },
  {
    id: 'fallback-tablet-meloxicam-15mg',
    name: 'Meloxicam 15mg',
    price: 24,
    description: 'Commonly used for meloxicam care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=800&auto=format&fit=crop',
    dosage: '15 mg',
    packQuantity: 10,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 95,
  },
  {
    id: 'fallback-tablet-pantoprazole-40mg',
    name: 'Pantoprazole 40mg',
    price: 39,
    description: 'Commonly used for pantoprazole care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173599ab14c?q=80&w=800&auto=format&fit=crop',
    dosage: '40 mg',
    packQuantity: 30,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 75,
  },
  {
    id: 'fallback-tablet-furosemide-40mg',
    name: 'Furosemide 40mg',
    price: 18,
    description: 'Commonly used for furosemide care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?q=80&w=800&auto=format&fit=crop',
    dosage: '40 mg',
    packQuantity: 20,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 130,
  },
  {
    id: 'fallback-tablet-clopidogrel-75mg',
    name: 'Clopidogrel 75mg',
    price: 48,
    description: 'Commonly used for clopidogrel care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?q=80&w=800&auto=format&fit=crop',
    dosage: '75 mg',
    packQuantity: 28,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 60,
  },
  {
    id: 'fallback-tablet-tamsulosin-0-4mg',
    name: 'Tamsulosin 0.4mg',
    price: 52,
    description: 'Commonly used for tamsulosin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?q=80&w=800&auto=format&fit=crop',
    dosage: '0.4 mg',
    packQuantity: 30,
    packUnit: 'tablets',
    category: 'tablet',
    stock: 45,
  },
  {
    id: 'fallback-capsule-omeprazole-20mg',
    name: 'Omeprazole 20mg',
    price: 48,
    description: 'Commonly used for omeprazole care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?q=80&w=800&auto=format&fit=crop',
    dosage: '20 mg',
    packQuantity: 15,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 60,
  },
  {
    id: 'fallback-capsule-amoxicillin-500mg',
    name: 'Amoxicillin 500mg',
    price: 65,
    description: 'Commonly used for amoxicillin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?q=80&w=800&auto=format&fit=crop',
    dosage: '500 mg',
    packQuantity: 15,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 45,
  },
  {
    id: 'fallback-capsule-fluoxetine-20mg',
    name: 'Fluoxetine 20mg',
    price: 35,
    description: 'Commonly used for fluoxetine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1584308914594-1f149527e597?q=80&w=800&auto=format&fit=crop',
    dosage: '20 mg',
    packQuantity: 30,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 80,
  },
  {
    id: 'fallback-capsule-duloxetine-30mg',
    name: 'Duloxetine 30mg',
    price: 58,
    description: 'Commonly used for duloxetine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?q=80&w=800&auto=format&fit=crop',
    dosage: '30 mg',
    packQuantity: 30,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 40,
  },
  {
    id: 'fallback-capsule-venlafaxine-75mg',
    name: 'Venlafaxine 75mg',
    price: 62,
    description: 'Commonly used for venlafaxine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?q=80&w=800&auto=format&fit=crop',
    dosage: '75 mg',
    packQuantity: 30,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 35,
  },
  {
    id: 'fallback-capsule-celecoxib-200mg',
    name: 'Celecoxib 200mg',
    price: 75,
    description: 'Commonly used for celecoxib care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1555633514-abcee6ab92e1?q=80&w=800&auto=format&fit=crop',
    dosage: '200 mg',
    packQuantity: 10,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 25,
  },
  {
    id: 'fallback-capsule-doxycycline-100mg',
    name: 'Doxycycline 100mg',
    price: 45,
    description: 'Commonly used for doxycycline care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=800&auto=format&fit=crop',
    dosage: '100 mg',
    packQuantity: 10,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 60,
  },
  {
    id: 'fallback-capsule-clindamycin-300mg',
    name: 'Clindamycin 300mg',
    price: 82,
    description: 'Commonly used for clindamycin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=800&auto=format&fit=crop',
    dosage: '300 mg',
    packQuantity: 15,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 20,
  },
  {
    id: 'fallback-capsule-gabapentin-capsule-300mg',
    name: 'Gabapentin Capsule 300mg',
    price: 55,
    description: 'Commonly used for gabapentin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?q=80&w=800&auto=format&fit=crop',
    dosage: '300 mg',
    packQuantity: 30,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 50,
  },
  {
    id: 'fallback-capsule-tamsulosin-capsule-0-4mg',
    name: 'Tamsulosin Capsule 0.4mg',
    price: 58,
    description: 'Commonly used for tamsulosin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=800&auto=format&fit=crop',
    dosage: '0.4 mg',
    packQuantity: 30,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 45,
  },
  {
    id: 'fallback-capsule-nitrofurantoin-100mg',
    name: 'Nitrofurantoin 100mg',
    price: 68,
    description: 'Commonly used for nitrofurantoin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=800&auto=format&fit=crop',
    dosage: '100 mg',
    packQuantity: 14,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 30,
  },
  {
    id: 'fallback-capsule-minocycline-50mg',
    name: 'Minocycline 50mg',
    price: 92,
    description: 'Commonly used for minocycline care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1502740479091-635887520276?q=80&w=800&auto=format&fit=crop',
    dosage: '50 mg',
    packQuantity: 30,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 15,
  },
  {
    id: 'fallback-capsule-pregabalin-75mg',
    name: 'Pregabalin 75mg',
    price: 72,
    description: 'Commonly used for pregabalin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=800&auto=format&fit=crop',
    dosage: '75 mg',
    packQuantity: 14,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 40,
  },
  {
    id: 'fallback-capsule-atomoxetine-40mg',
    name: 'Atomoxetine 40mg',
    price: 110,
    description: 'Commonly used for atomoxetine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1579154235602-3c2c2992d216?q=80&w=800&auto=format&fit=crop',
    dosage: '40 mg',
    packQuantity: 30,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 10,
  },
  {
    id: 'fallback-capsule-fluconazole-150mg',
    name: 'Fluconazole 150mg',
    price: 45,
    description: 'Commonly used for fluconazole care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1583912267550-d44d7a12982c?q=80&w=800&auto=format&fit=crop',
    dosage: '150 mg',
    packQuantity: 1,
    packUnit: 'capsule',
    category: 'capsule',
    stock: 90,
  },
  {
    id: 'fallback-capsule-lansoprazole-30mg',
    name: 'Lansoprazole 30mg',
    price: 52,
    description: 'Commonly used for lansoprazole care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=800&auto=format&fit=crop',
    dosage: '30 mg',
    packQuantity: 30,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 55,
  },
  {
    id: 'fallback-capsule-cephalexin-500mg',
    name: 'Cephalexin 500mg',
    price: 38,
    description: 'Commonly used for cephalexin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f593ed33?q=80&w=800&auto=format&fit=crop',
    dosage: '500 mg',
    packQuantity: 20,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 70,
  },
  {
    id: 'fallback-capsule-azithromycin-capsule-250mg',
    name: 'Azithromycin Capsule 250mg',
    price: 95,
    description: 'Commonly used for azithromycin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1556228578-0f85f1a9d59c?q=80&w=800&auto=format&fit=crop',
    dosage: '250 mg',
    packQuantity: 6,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 25,
  },
  {
    id: 'fallback-capsule-itraconazole-100mg',
    name: 'Itraconazole 100mg',
    price: 125,
    description: 'Commonly used for itraconazole care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?q=80&w=800&auto=format&fit=crop',
    dosage: '100 mg',
    packQuantity: 10,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 15,
  },
  {
    id: 'fallback-capsule-vitamin-d3-60k',
    name: 'Vitamin D3 60K',
    price: 30,
    description: 'Commonly used for vitamin d3 care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?q=80&w=800&auto=format&fit=crop',
    dosage: '60000 IU',
    packQuantity: 4,
    packUnit: 'capsules',
    category: 'capsule',
    stock: 200,
  },
  {
    id: 'fallback-syrup-cough-relief-syrup',
    name: 'Cough Relief Syrup',
    price: 95,
    description: 'Commonly used for dextromethorphan care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1616627561950-9f746e330187?q=80&w=800&auto=format&fit=crop',
    dosage: '100 ml',
    packQuantity: 100,
    packUnit: 'ml',
    category: 'syrup',
    stock: 35,
  },
  {
    id: 'fallback-syrup-paracetamol-pediatric-syrup',
    name: 'Paracetamol Pediatric Syrup',
    price: 45,
    description: 'Commonly used for paracetamol care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?q=80&w=800&auto=format&fit=crop',
    dosage: '60 ml',
    packQuantity: 60,
    packUnit: 'ml',
    category: 'syrup',
    stock: 120,
  },
  {
    id: 'fallback-syrup-ambroxol-syrup-30mg-5ml',
    name: 'Ambroxol Syrup 30mg/5ml',
    price: 78,
    description: 'Commonly used for ambroxol care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1588200908304-42918898116b?q=80&w=800&auto=format&fit=crop',
    dosage: '100 ml',
    packQuantity: 100,
    packUnit: 'ml',
    category: 'syrup',
    stock: 50,
  },
  {
    id: 'fallback-syrup-salbutamol-syrup',
    name: 'Salbutamol Syrup',
    price: 35,
    description: 'Commonly used for salbutamol care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1584515982849-02eb4b280927?q=80&w=800&auto=format&fit=crop',
    dosage: '100 ml',
    packQuantity: 100,
    packUnit: 'ml',
    category: 'syrup',
    stock: 80,
  },
  {
    id: 'fallback-syrup-levocetirizine-syrup',
    name: 'Levocetirizine Syrup',
    price: 62,
    description: 'Commonly used for levocetirizine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1581093588401-f3c22d73b2e9?q=80&w=800&auto=format&fit=crop',
    dosage: '60 ml',
    packQuantity: 60,
    packUnit: 'ml',
    category: 'syrup',
    stock: 65,
  },
  {
    id: 'fallback-syrup-sucralfate-suspension',
    name: 'Sucralfate Suspension',
    price: 120,
    description: 'Commonly used for sucralfate care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1581349485608-947ab992e67f?q=80&w=800&auto=format&fit=crop',
    dosage: '200 ml',
    packQuantity: 200,
    packUnit: 'ml',
    category: 'syrup',
    stock: 25,
  },
  {
    id: 'fallback-syrup-multivitamin-health-tonic',
    name: 'Multivitamin Health Tonic',
    price: 150,
    description: 'Commonly used for multivitamin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1579684275623-0d22097b27d3?q=80&w=800&auto=format&fit=crop',
    dosage: '225 ml',
    packQuantity: 225,
    packUnit: 'ml',
    category: 'syrup',
    stock: 40,
  },
  {
    id: 'fallback-syrup-milk-of-magnesia',
    name: 'Milk of Magnesia',
    price: 85,
    description: 'Commonly used for magnesium hydroxide care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=800&auto=format&fit=crop',
    dosage: '170 ml',
    packQuantity: 170,
    packUnit: 'ml',
    category: 'syrup',
    stock: 60,
  },
  {
    id: 'fallback-syrup-ayurvedic-cough-syrup',
    name: 'Ayurvedic Cough Syrup',
    price: 110,
    description: 'Commonly used for ficus religiosa care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?q=80&w=800&auto=format&fit=crop',
    dosage: '100 ml',
    packQuantity: 100,
    packUnit: 'ml',
    category: 'syrup',
    stock: 45,
  },
  {
    id: 'fallback-syrup-iron-folic-acid-syrup',
    name: 'Iron & Folic Acid Syrup',
    price: 175,
    description: 'Commonly used for ferrous ascorbate care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1579684453423-f84349ef1a2e?q=80&w=800&auto=format&fit=crop',
    dosage: '200 ml',
    packQuantity: 200,
    packUnit: 'ml',
    category: 'syrup',
    stock: 30,
  },
  {
    id: 'fallback-syrup-calcium-syrup-with-vit-d3',
    name: 'Calcium Syrup with Vit D3',
    price: 135,
    description: 'Commonly used for calcium gluconate care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=800&auto=format&fit=crop',
    dosage: '200 ml',
    packQuantity: 200,
    packUnit: 'ml',
    category: 'syrup',
    stock: 55,
  },
  {
    id: 'fallback-syrup-alkalizer-syrup',
    name: 'Alkalizer Syrup',
    price: 92,
    description: 'Commonly used for disodium hydrogen citrate care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1582560475093-ba66accbc424?q=80&w=800&auto=format&fit=crop',
    dosage: '100 ml',
    packQuantity: 100,
    packUnit: 'ml',
    category: 'syrup',
    stock: 70,
  },
  {
    id: 'fallback-syrup-appetite-stimulant-syrup',
    name: 'Appetite Stimulant Syrup',
    price: 105,
    description: 'Commonly used for cyproheptadine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?q=80&w=800&auto=format&fit=crop',
    dosage: '200 ml',
    packQuantity: 200,
    packUnit: 'ml',
    category: 'syrup',
    stock: 40,
  },
  {
    id: 'fallback-syrup-lactulose-oral-solution',
    name: 'Lactulose Oral Solution',
    price: 210,
    description: 'Commonly used for lactulose care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=800&auto=format&fit=crop',
    dosage: '200 ml',
    packQuantity: 200,
    packUnit: 'ml',
    category: 'syrup',
    stock: 20,
  },
  {
    id: 'fallback-syrup-ondansetron-drops',
    name: 'Ondansetron Drops',
    price: 48,
    description: 'Commonly used for ondansetron care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1518152006812-edab29b069ac?q=80&w=800&auto=format&fit=crop',
    dosage: '30 ml',
    packQuantity: 30,
    packUnit: 'ml',
    category: 'syrup',
    stock: 100,
  },
  {
    id: 'fallback-syrup-domperidone-suspension',
    name: 'Domperidone Suspension',
    price: 55,
    description: 'Commonly used for domperidone care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1579684385103-68d71683be8a?q=80&w=800&auto=format&fit=crop',
    dosage: '30 ml',
    packQuantity: 30,
    packUnit: 'ml',
    category: 'syrup',
    stock: 85,
  },
  {
    id: 'fallback-syrup-albendazole-oral-suspension',
    name: 'Albendazole Oral Suspension',
    price: 28,
    description: 'Commonly used for albendazole care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1631248055158-edec7a3c072b?q=80&w=800&auto=format&fit=crop',
    dosage: '10 ml',
    packQuantity: 10,
    packUnit: 'ml',
    category: 'syrup',
    stock: 150,
  },
  {
    id: 'fallback-syrup-metronidazole-suspension',
    name: 'Metronidazole Suspension',
    price: 42,
    description: 'Commonly used for metronidazole care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1632833239869-a37e31580662?q=80&w=800&auto=format&fit=crop',
    dosage: '60 ml',
    packQuantity: 60,
    packUnit: 'ml',
    category: 'syrup',
    stock: 95,
  },
  {
    id: 'fallback-syrup-b-complex-syrup',
    name: 'B-Complex Syrup',
    price: 88,
    description: 'Commonly used for b-complex care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1632833239016-df83a0774514?q=80&w=800&auto=format&fit=crop',
    dosage: '200 ml',
    packQuantity: 200,
    packUnit: 'ml',
    category: 'syrup',
    stock: 110,
  },
  {
    id: 'fallback-syrup-mint-antacid-liquid',
    name: 'Mint Antacid Liquid',
    price: 75,
    description: 'Commonly used for antacid care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1584362946551-7890f507b941?q=80&w=800&auto=format&fit=crop',
    dosage: '170 ml',
    packQuantity: 170,
    packUnit: 'ml',
    category: 'syrup',
    stock: 130,
  },
  {
    id: 'fallback-cream-clotrimazole-cream',
    name: 'Clotrimazole Cream',
    price: 68,
    description: 'Commonly used for clotrimazole care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop',
    dosage: '1% w/w',
    packQuantity: 30,
    packUnit: 'g',
    category: 'cream',
    stock: 40,
  },
  {
    id: 'fallback-cream-pain-relief-gel',
    name: 'Pain Relief Gel',
    price: 85,
    description: 'Commonly used for diclofenac care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop',
    dosage: '30 g',
    packQuantity: 30,
    packUnit: 'g',
    category: 'cream',
    stock: 55,
  },
  {
    id: 'fallback-cream-hydrocortisone-cream-1',
    name: 'Hydrocortisone Cream 1%',
    price: 42,
    description: 'Commonly used for hydrocortisone care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=800&auto=format&fit=crop',
    dosage: '15 g',
    packQuantity: 15,
    packUnit: 'g',
    category: 'cream',
    stock: 100,
  },
  {
    id: 'fallback-cream-mupirocin-ointment',
    name: 'Mupirocin Ointment',
    price: 145,
    description: 'Commonly used for mupirocin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1618331835717-801697867623?q=80&w=800&auto=format&fit=crop',
    dosage: '5 g',
    packQuantity: 5,
    packUnit: 'g',
    category: 'cream',
    stock: 25,
  },
  {
    id: 'fallback-cream-ketoconazole-cream-2',
    name: 'Ketoconazole Cream 2%',
    price: 115,
    description: 'Commonly used for ketoconazole care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=800&auto=format&fit=crop',
    dosage: '30 g',
    packQuantity: 30,
    packUnit: 'g',
    category: 'cream',
    stock: 35,
  },
  {
    id: 'fallback-cream-adapalene-gel-0-1',
    name: 'Adapalene Gel 0.1%',
    price: 210,
    description: 'Commonly used for adapalene care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop',
    dosage: '15 g',
    packQuantity: 15,
    packUnit: 'g',
    category: 'cream',
    stock: 20,
  },
  {
    id: 'fallback-cream-benzoyl-peroxide-gel-5',
    name: 'Benzoyl Peroxide Gel 5%',
    price: 125,
    description: 'Commonly used for benzoyl peroxide care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1556228578-0f85f1a9d59c-cream?q=80&w=800&auto=format&fit=crop',
    dosage: '20 g',
    packQuantity: 20,
    packUnit: 'g',
    category: 'cream',
    stock: 45,
  },
  {
    id: 'fallback-cream-betamethasone-skin-cream',
    name: 'Betamethasone Skin Cream',
    price: 38,
    description: 'Commonly used for betamethasone care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
    dosage: '20 g',
    packQuantity: 20,
    packUnit: 'g',
    category: 'cream',
    stock: 90,
  },
  {
    id: 'fallback-cream-fusidic-acid-cream',
    name: 'Fusidic Acid Cream',
    price: 155,
    description: 'Commonly used for fusidic acid care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=800&auto=format&fit=crop',
    dosage: '10 g',
    packQuantity: 10,
    packUnit: 'g',
    category: 'cream',
    stock: 30,
  },
  {
    id: 'fallback-cream-terbinafine-cream-1',
    name: 'Terbinafine Cream 1%',
    price: 135,
    description: 'Commonly used for terbinafine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=800&auto=format&fit=crop',
    dosage: '10 g',
    packQuantity: 10,
    packUnit: 'g',
    category: 'cream',
    stock: 40,
  },
  {
    id: 'fallback-cream-permethrin-cream-5',
    name: 'Permethrin Cream 5%',
    price: 95,
    description: 'Commonly used for permethrin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?q=80&w=800&auto=format&fit=crop',
    dosage: '30 g',
    packQuantity: 30,
    packUnit: 'g',
    category: 'cream',
    stock: 60,
  },
  {
    id: 'fallback-cream-silver-sulfadiazine-burn-cream',
    name: 'Silver Sulfadiazine Burn Cream',
    price: 110,
    description: 'Commonly used for silver sulfadiazine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=800&auto=format&fit=crop',
    dosage: '25 g',
    packQuantity: 25,
    packUnit: 'g',
    category: 'cream',
    stock: 50,
  },
  {
    id: 'fallback-cream-miconazole-nitrate-cream',
    name: 'Miconazole Nitrate Cream',
    price: 72,
    description: 'Commonly used for miconazole care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1620917670397-dc7bc40e7292?q=80&w=800&auto=format&fit=crop',
    dosage: '15 g',
    packQuantity: 15,
    packUnit: 'g',
    category: 'cream',
    stock: 75,
  },
  {
    id: 'fallback-cream-tretinoin-cream-0-025',
    name: 'Tretinoin Cream 0.025%',
    price: 185,
    description: 'Commonly used for tretinoin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1508750804132-b783f276cb5e?q=80&w=800&auto=format&fit=crop',
    dosage: '20 g',
    packQuantity: 20,
    packUnit: 'g',
    category: 'cream',
    stock: 25,
  },
  {
    id: 'fallback-cream-beclomethasone-dipropionate',
    name: 'Beclomethasone Dipropionate',
    price: 45,
    description: 'Commonly used for beclomethasone care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1606206750302-36c57f79430c?q=80&w=800&auto=format&fit=crop',
    dosage: '15 g',
    packQuantity: 15,
    packUnit: 'g',
    category: 'cream',
    stock: 110,
  },
  {
    id: 'fallback-cream-clobetasol-propionate-ointment',
    name: 'Clobetasol Propionate Ointment',
    price: 58,
    description: 'Commonly used for clobetasol care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1614859324883-7d31853db5bb?q=80&w=800&auto=format&fit=crop',
    dosage: '30 g',
    packQuantity: 30,
    packUnit: 'g',
    category: 'cream',
    stock: 95,
  },
  {
    id: 'fallback-cream-antiseptic-ointment',
    name: 'Antiseptic Ointment',
    price: 65,
    description: 'Commonly used for povidone-iodine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1619451422736-248c847a61d1?q=80&w=800&auto=format&fit=crop',
    dosage: '15 g',
    packQuantity: 15,
    packUnit: 'g',
    category: 'cream',
    stock: 120,
  },
  {
    id: 'fallback-cream-thrombophob-gel',
    name: 'Thrombophob Gel',
    price: 142,
    description: 'Commonly used for heparin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1621021487834-31dc60c3e1e8?q=80&w=800&auto=format&fit=crop',
    dosage: '20 g',
    packQuantity: 20,
    packUnit: 'g',
    category: 'cream',
    stock: 30,
  },
  {
    id: 'fallback-cream-calamine-lotion',
    name: 'Calamine Lotion',
    price: 88,
    description: 'Commonly used for calamine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c-cream?q=80&w=800&auto=format&fit=crop',
    dosage: '100 ml',
    packQuantity: 100,
    packUnit: 'ml',
    category: 'cream',
    stock: 85,
  },
  {
    id: 'fallback-cream-soothing-aloe-vera-gel',
    name: 'Soothing Aloe Vera Gel',
    price: 120,
    description: 'Commonly used for aloevera care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528-cream?q=80&w=800&auto=format&fit=crop',
    dosage: '150 g',
    packQuantity: 150,
    packUnit: 'g',
    category: 'cream',
    stock: 70,
  },
  {
    id: 'fallback-drops-lubricating-eye-drops',
    name: 'Lubricating Eye Drops',
    price: 145,
    description: 'Commonly used for carboxymethylcellulose care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1536924940846-227afb31e2a5?q=80&w=800&auto=format&fit=crop',
    dosage: '10 ml',
    packQuantity: 10,
    packUnit: 'ml',
    category: 'drops',
    stock: 50,
  },
  {
    id: 'fallback-drops-timolol-eye-drops-0-5',
    name: 'Timolol Eye Drops 0.5%',
    price: 92,
    description: 'Commonly used for timolol care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1601049676099-e7ed07d825b0?q=80&w=800&auto=format&fit=crop',
    dosage: '5 ml',
    packQuantity: 5,
    packUnit: 'ml',
    category: 'drops',
    stock: 40,
  },
  {
    id: 'fallback-drops-cipro-ear-eye-drops',
    name: 'Cipro Ear/Eye Drops',
    price: 35,
    description: 'Commonly used for ciprofloxacin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1542736667-069246bdd671?q=80&w=800&auto=format&fit=crop',
    dosage: '5 ml',
    packQuantity: 5,
    packUnit: 'ml',
    category: 'drops',
    stock: 150,
  },
  {
    id: 'fallback-drops-naphazoline-eye-drops',
    name: 'Naphazoline Eye Drops',
    price: 48,
    description: 'Commonly used for naphazoline care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=800&auto=format&fit=crop',
    dosage: '10 ml',
    packQuantity: 10,
    packUnit: 'ml',
    category: 'drops',
    stock: 120,
  },
  {
    id: 'fallback-drops-brimonidine-eye-drops-0-2',
    name: 'Brimonidine Eye Drops 0.2%',
    price: 210,
    description: 'Commonly used for brimonidine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1551244072-5d12893278ab?q=80&w=800&auto=format&fit=crop',
    dosage: '5 ml',
    packQuantity: 5,
    packUnit: 'ml',
    category: 'drops',
    stock: 25,
  },
  {
    id: 'fallback-drops-loteprednol-eye-drops',
    name: 'Loteprednol Eye Drops',
    price: 345,
    description: 'Commonly used for loteprednol care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1590611358583-373b5f486241?q=80&w=800&auto=format&fit=crop',
    dosage: '5 ml',
    packQuantity: 5,
    packUnit: 'ml',
    category: 'drops',
    stock: 15,
  },
  {
    id: 'fallback-drops-moxifloxacin-eye-drops',
    name: 'Moxifloxacin Eye Drops',
    price: 125,
    description: 'Commonly used for moxifloxacin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1550831107-1553da8c8464?q=80&w=800&auto=format&fit=crop',
    dosage: '5 ml',
    packQuantity: 5,
    packUnit: 'ml',
    category: 'drops',
    stock: 65,
  },
  {
    id: 'fallback-drops-nasal-decongestant-drops',
    name: 'Nasal Decongestant Drops',
    price: 55,
    description: 'Commonly used for xylometazoline care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=800&auto=format&fit=crop',
    dosage: '10 ml',
    packQuantity: 10,
    packUnit: 'ml',
    category: 'drops',
    stock: 95,
  },
  {
    id: 'fallback-drops-saline-nasal-drops',
    name: 'Saline Nasal Drops',
    price: 28,
    description: 'Commonly used for saline care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=800&auto=format&fit=crop',
    dosage: '15 ml',
    packQuantity: 15,
    packUnit: 'ml',
    category: 'drops',
    stock: 200,
  },
  {
    id: 'fallback-drops-ofloxacin-ear-drops',
    name: 'Ofloxacin Ear Drops',
    price: 42,
    description: 'Commonly used for ofloxacin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1584467541268-b040f83be3fd?q=80&w=800&auto=format&fit=crop',
    dosage: '5 ml',
    packQuantity: 5,
    packUnit: 'ml',
    category: 'drops',
    stock: 110,
  },
  {
    id: 'fallback-drops-prednisolone-eye-drops',
    name: 'Prednisolone Eye Drops',
    price: 85,
    description: 'Commonly used for prednisolone care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1588429177114-1e03b79bba8?q=80&w=800&auto=format&fit=crop',
    dosage: '5 ml',
    packQuantity: 5,
    packUnit: 'ml',
    category: 'drops',
    stock: 55,
  },
  {
    id: 'fallback-drops-gentamicin-eye-ear-drops',
    name: 'Gentamicin Eye/Ear Drops',
    price: 22,
    description: 'Commonly used for gentamicin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1504813184591-015570107fd5?q=80&w=800&auto=format&fit=crop',
    dosage: '10 ml',
    packQuantity: 10,
    packUnit: 'ml',
    category: 'drops',
    stock: 180,
  },
  {
    id: 'fallback-drops-flurbiprofen-eye-drops',
    name: 'Flurbiprofen Eye Drops',
    price: 115,
    description: 'Commonly used for flurbiprofen care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=800&auto=format&fit=crop',
    dosage: '5 ml',
    packQuantity: 5,
    packUnit: 'ml',
    category: 'drops',
    stock: 35,
  },
  {
    id: 'fallback-drops-olopatadine-eye-drops',
    name: 'Olopatadine Eye Drops',
    price: 195,
    description: 'Commonly used for olopatadine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=800&auto=format&fit=crop',
    dosage: '5 ml',
    packQuantity: 5,
    packUnit: 'ml',
    category: 'drops',
    stock: 30,
  },
  {
    id: 'fallback-drops-dorzolamide-eye-drops',
    name: 'Dorzolamide Eye Drops',
    price: 255,
    description: 'Commonly used for dorzolamide care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=800&auto=format&fit=crop',
    dosage: '5 ml',
    packQuantity: 5,
    packUnit: 'ml',
    category: 'drops',
    stock: 20,
  },
  {
    id: 'fallback-drops-tobramycin-eye-drops',
    name: 'Tobramycin Eye Drops',
    price: 135,
    description: 'Commonly used for tobramycin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1592595896551-12b371d546d5?q=80&w=800&auto=format&fit=crop',
    dosage: '5 ml',
    packQuantity: 5,
    packUnit: 'ml',
    category: 'drops',
    stock: 45,
  },
  {
    id: 'fallback-drops-ear-wax-dissolvent-drops',
    name: 'Ear Wax Dissolvent Drops',
    price: 65,
    description: 'Commonly used for clotrimazole ear care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    dosage: '10 ml',
    packQuantity: 10,
    packUnit: 'ml',
    category: 'drops',
    stock: 85,
  },
  {
    id: 'fallback-drops-antiseptic-eye-wash',
    name: 'Antiseptic Eye Wash',
    price: 78,
    description: 'Commonly used for boric acid care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?q=80&w=800&auto=format&fit=crop',
    dosage: '10 ml',
    packQuantity: 10,
    packUnit: 'ml',
    category: 'drops',
    stock: 60,
  },
  {
    id: 'fallback-drops-ear-relief-drops',
    name: 'Ear Relief Drops',
    price: 110,
    description: 'Commonly used for fluocinolone care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1612531386530-97286d97c2d2?q=80&w=800&auto=format&fit=crop',
    dosage: '5 ml',
    packQuantity: 5,
    packUnit: 'ml',
    category: 'drops',
    stock: 40,
  },
  {
    id: 'fallback-drops-premium-tear-substitute',
    name: 'Premium Tear Substitute',
    price: 420,
    description: 'Commonly used for hyaluronic acid care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?q=80&w=800&auto=format&fit=crop',
    dosage: '10 ml',
    packQuantity: 10,
    packUnit: 'ml',
    category: 'drops',
    stock: 20,
  },
  {
    id: 'fallback-injection-insulin-glargine',
    name: 'Insulin Glargine',
    price: 450,
    description: 'Commonly used for insulin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?q=80&w=800&auto=format&fit=crop',
    dosage: '10 ml vial',
    packQuantity: 1,
    packUnit: 'vial',
    category: 'injection',
    stock: 18,
  },
  {
    id: 'fallback-injection-ceftriaxone-injection-1g',
    name: 'Ceftriaxone Injection 1g',
    price: 65,
    description: 'Commonly used for ceftriaxone care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1513836279014-a89f77ee1991?q=80&w=800&auto=format&fit=crop',
    dosage: '1 g',
    packQuantity: 1,
    packUnit: 'vial',
    category: 'injection',
    stock: 45,
  },
  {
    id: 'fallback-injection-diclofenac-injection',
    name: 'Diclofenac Injection',
    price: 15,
    description: 'Commonly used for diclofenac injection care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?q=80&w=800&auto=format&fit=crop',
    dosage: '3 ml ampoule',
    packQuantity: 1,
    packUnit: 'ampoule',
    category: 'injection',
    stock: 200,
  },
  {
    id: 'fallback-injection-pantoprazole-injection',
    name: 'Pantoprazole Injection',
    price: 62,
    description: 'Commonly used for pantoprazole intravenous care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?q=80&w=800&auto=format&fit=crop',
    dosage: '40 mg',
    packQuantity: 1,
    packUnit: 'vial',
    category: 'injection',
    stock: 80,
  },
  {
    id: 'fallback-injection-vit-b12-methylcobalamin',
    name: 'Vit B12 (Methylcobalamin)',
    price: 28,
    description: 'Commonly used for vitamin b12 care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1472214222541-d510753a4907?q=80&w=800&auto=format&fit=crop',
    dosage: '2 ml ampoule',
    packQuantity: 1,
    packUnit: 'ampoule',
    category: 'injection',
    stock: 150,
  },
  {
    id: 'fallback-injection-enoxaparin-prefilled-syringe',
    name: 'Enoxaparin Prefilled Syringe',
    price: 580,
    description: 'Commonly used for enoxaparin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=800&auto=format&fit=crop',
    dosage: '0.6 ml',
    packQuantity: 1,
    packUnit: 'syringe',
    category: 'injection',
    stock: 12,
  },
  {
    id: 'fallback-injection-clindamycin-injection',
    name: 'Clindamycin Injection',
    price: 125,
    description: 'Commonly used for clindamycin injection care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?q=80&w=800&auto=format&fit=crop',
    dosage: '600 mg',
    packQuantity: 1,
    packUnit: 'vial',
    category: 'injection',
    stock: 35,
  },
  {
    id: 'fallback-injection-furosemide-injection',
    name: 'Furosemide Injection',
    price: 12,
    description: 'Commonly used for furosemide injection care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=800&auto=format&fit=crop',
    dosage: '2 ml ampoule',
    packQuantity: 1,
    packUnit: 'ampoule',
    category: 'injection',
    stock: 250,
  },
  {
    id: 'fallback-injection-iron-sucrose-injection',
    name: 'Iron Sucrose Injection',
    price: 320,
    description: 'Commonly used for iron sucrose care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=800&auto=format&fit=crop',
    dosage: '5 ml ampoule',
    packQuantity: 1,
    packUnit: 'ampoule',
    category: 'injection',
    stock: 25,
  },
  {
    id: 'fallback-injection-dexamethasone-injection',
    name: 'Dexamethasone Injection',
    price: 10,
    description: 'Commonly used for dexamethasone care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=800&auto=format&fit=crop',
    dosage: '2 ml vial',
    packQuantity: 1,
    packUnit: 'vial',
    category: 'injection',
    stock: 300,
  },
  {
    id: 'fallback-injection-ondansetron-injection',
    name: 'Ondansetron Injection',
    price: 18,
    description: 'Commonly used for ondansetron injection care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?q=80&w=800&auto=format&fit=crop',
    dosage: '2 ml ampoule',
    packQuantity: 1,
    packUnit: 'ampoule',
    category: 'injection',
    stock: 180,
  },
  {
    id: 'fallback-injection-gentamicin-injection-80mg',
    name: 'Gentamicin Injection 80mg',
    price: 15,
    description: 'Commonly used for gentamicin injection care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?q=80&w=800&auto=format&fit=crop',
    dosage: '2 ml vial',
    packQuantity: 1,
    packUnit: 'vial',
    category: 'injection',
    stock: 220,
  },
  {
    id: 'fallback-injection-heparin-sodium-injection',
    name: 'Heparin Sodium Injection',
    price: 245,
    description: 'Commonly used for heparin sodium care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05-inj?q=80&w=800&auto=format&fit=crop',
    dosage: '5000 IU/ml',
    packQuantity: 5,
    packUnit: 'vial',
    category: 'injection',
    stock: 30,
  },
  {
    id: 'fallback-injection-atropine-sulphate',
    name: 'Atropine Sulphate',
    price: 14,
    description: 'Commonly used for atropine care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1472214222541-d510753a4907-inj?q=80&w=800&auto=format&fit=crop',
    dosage: '1 ml ampoule',
    packQuantity: 1,
    packUnit: 'ampoule',
    category: 'injection',
    stock: 150,
  },
  {
    id: 'fallback-injection-tranexamic-acid-injection',
    name: 'Tranexamic Acid Injection',
    price: 95,
    description: 'Commonly used for tranexamic acid care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?q=80&w=800&auto=format&fit=crop',
    dosage: '5 ml ampoule',
    packQuantity: 1,
    packUnit: 'ampoule',
    category: 'injection',
    stock: 55,
  },
  {
    id: 'fallback-injection-meropenem-injection-1g',
    name: 'Meropenem Injection 1g',
    price: 850,
    description: 'Commonly used for meropenem care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?q=80&w=800&auto=format&fit=crop',
    dosage: '1 g',
    packQuantity: 1,
    packUnit: 'vial',
    category: 'injection',
    stock: 8,
  },
  {
    id: 'fallback-injection-piperacillin-tazobactam',
    name: 'Piperacillin Tazobactam',
    price: 420,
    description: 'Commonly used for piperacillin care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
    dosage: '4.5 g',
    packQuantity: 1,
    packUnit: 'vial',
    category: 'injection',
    stock: 20,
  },
  {
    id: 'fallback-injection-metoclopramide-injection',
    name: 'Metoclopramide Injection',
    price: 12,
    description: 'Commonly used for metoclopramide care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?q=80&w=800&auto=format&fit=crop',
    dosage: '2 ml ampoule',
    packQuantity: 1,
    packUnit: 'ampoule',
    category: 'injection',
    stock: 180,
  },
  {
    id: 'fallback-injection-levofloxacin-intravenous',
    name: 'Levofloxacin Intravenous',
    price: 185,
    description: 'Commonly used for levofloxacin injection care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1513836279014-a89f77ee1991-inj?q=80&w=800&auto=format&fit=crop',
    dosage: '100 ml IV',
    packQuantity: 1,
    packUnit: 'bottle',
    category: 'injection',
    stock: 30,
  },
  {
    id: 'fallback-injection-tetanus-vaccine',
    name: 'Tetanus Vaccine',
    price: 35,
    description: 'Commonly used for tetanus toxoid care. Consult a doctor or pharmacist before use.',
    manufacturer: 'Bablu Medical Essentials',
    sourceName: 'Built-in store catalog',
    sourceUrl: '',
    imageUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9-inj?q=80&w=800&auto=format&fit=crop',
    dosage: '0.5 ml',
    packQuantity: 1,
    packUnit: 'ampoule',
    category: 'injection',
    stock: 100,
  }
];
